### ISSUE TITLE
Release v0.0.3

### ISSUE THREAD

**Issue by jkintscher** [jsonapi-rb/jsonapi-rspec#16]
Hey, thanks for writing and maintaining this gem! While 0.0.3 already exists as a tag on Github, it’s not yet cut and released as a new version to RubyGems.

Would you mind releasing it, given the latest version includes several fixes, _e.g._ fixing the rspec-expectations lazy loading issue in `test`, and improvements to the assertions, _e.g._ `#have_jsonapi_attributes`?

Installing from the repo directly is just less ideal and sometimes not even a possibility, depending on security policy.

Thanks!

**Comment by stas** [comment]
Thanks @jkintscher, unfortunately I don't have access to the Rubygems and @beauby could not find time yet to assist with this. If there are other maintainers or folks with access here, please leave a note or get in touch.

Stay safe all! :hugs:
