### ISSUE TITLE
have_attributes matcher clashes with rspec-expectations v3.4.0

### ISSUE THREAD

**Issue by gabrielgasser** [jsonapi-rb/jsonapi-rspec#4]
Thanks for this gem, it's really helpful.

The matcher have_attributes clashes with rspec-expectations v3.4.0. I reckon it would be nice to have something like have_jsonapi_attributes or similar.

Cheers.

**Comment by caseyprovost** [comment]
Just ran into this today as well.

**Comment by stas** [comment]
We'll provide a fix in the next release...
